staging-settings:
  user-workflow:
    workflow-name: latch-confidential-policy-staging
  workflow-artifacts:
    workflow-path: "./src/main.ts"
    config-path: "./config.staging.json"
    secrets-path: "./secrets.yaml"
